### PR TITLE
Add new connection strategies and mark strategy as required

### PR DESCRIPTION
**Pull request by dmcgee-ripple**
New values (`apple`, `oidc`, `line`) are from the documentation. I left the string list in the code in the same non-alphabetical order as the upstream documentation so it is easier to see what might change in the future.
https://auth0.com/docs/api/management/v2#!/Connections/post_connections

Additionally, `strategy` has been marked as required as the API states
it is a mandatory parameter.

Open question- does it make sense to validate these since the list can continue to be updated in the future? Or is there a validator that will warn (but not reject) unknown but possibly valid values?

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by benjigoldberg** [comment]
I just came here to see if this was under development! +1 would love this functionality. Thank you for contributing this!

**Comment by dmcgee-ripple** [comment]
I'm not sure what is going on with the `Label` Github action, but maybe it isn't working since this PR is in a fork? Let me know if there is something I need to do to make that work.

**Comment by alexkappa** [comment]
Hi Dan, thank you for submitting this! I'll give it a test and merge it in.

> Or is there a validator that will warn (but not reject) unknown but possibly valid values?

Indeed, there is a warning mechanism we can use. We just need to write it ourselves cause the terraform sdk doesn't come with one as far as I know. It's probably a good idea to do that, so we can support new connection types as they become available.

**Comment by benjigoldberg** [comment]
@alexkappa thanks for merging this! Any chance we could cut a new release? We'd love to take advantage of this feature

**Comment by alexkappa** [comment]
I asked hashicorp for a new release but they haven't gotten around to it yet. I will ping again.

Meanwhile you could use the [v0.5.2](https://github.com/alexkappa/terraform-provider-auth0/releases/tag/v0.5.2) from the original repository.

**Pull request merged**
